import Head from 'next/head'
//import Image from 'next/image'
//import styles from '../styles/Home.module.css'
import { Button } from '@chakra-ui/react'
import Link from 'next/link'
import { Header } from '../components/Header'
import Home from '../components/Home'
import { useStateContext, useSetStateContext } from '../modules/Context'
import { Avatar, Image } from '@chakra-ui/react'

export default function Index() {
  const count = useStateContext()
  const dispatch = useSetStateContext()

  const handleIncrease = event => dispatch(count + 1)
  const handleDecrease = event => dispatch(count - 1)
  const session = {
    user: {
      name: 'Dre Crego',
      email: 'drecrego@gmail.com',
      image:
        'https://lh3.googleusercontent.com/a/ALm5wu2QqOdUCaDDCN-SdnPT4aPCvOH8QZQ0nvAsZ5XW=s96-c',
      id: '6373de19f792a083e020c28f',
    },
    expires: '2022-12-18T18:48:10.021Z',
  }
  return (
    <div>
      <Head>
        <title>AC Demo Next.js </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nira.png" />
      </Head>
      <Home />
    </div>
  )
}
